name = "aifreecalculator"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Cloudflare D1 Database Binding
[[d1_databases]]
binding = "DB"
database_name = "aifreecalculator_db"
database_id = "b130d2d6-11f5-4852-9ab3-36644d3948c7"

[vars]
PUBLIC_SITE_NAME = "AI Free Calculator"
PUBLIC_SITE_URL = "https://aifreecalculator.com"
