import fs from 'fs';
import path from 'path';
const D = 'src/i18n/translations/calculators/data';
const MIN = 3000;
const rd = p => JSON.parse(fs.readFileSync(path.join(D,p+'.json'),'utf8'));
const wr = (p,d) => fs.writeFileSync(path.join(D,p+'.json'),JSON.stringify(d,null,2),'utf8');
function fix(d,loc,html){ if(!d[loc])d[loc]={}; if((d[loc].contentHtml||'').length<MIN){d[loc].contentHtml=html;return true;}return false;}
let n=0;

// Helper: generate tool page HTML
function mkTool(t){
  return [
    '<div class="space-y-8 text-slate-700 dark:text-slate-300 not-prose">',
    '<section class="space-y-4">',
    `<h2 class="text-2xl font-bold text-slate-900 dark:text-white">${t.h1}</h2>`,
    `<p class="leading-relaxed">${t.d}</p>`,
    '</section>',
    '<section class="space-y-4">',
    `<h2 class="text-xl font-bold text-slate-900 dark:text-white">${t.hh}</h2>`,
    '<ol class="list-decimal pl-5 space-y-2">',
    ...t.s.map(x=>`<li>${x}</li>`),
    '</ol></section>',
    '<section class="space-y-4">',
    `<h2 class="text-xl font-bold text-slate-900 dark:text-white">${t.fh}</h2>`,
    '<ul class="list-disc pl-5 space-y-2">',
    ...t.f.map(x=>`<li>${x}</li>`),
    '</ul></section>',
    '<section class="space-y-4">',
    '<h2 class="text-xl font-bold text-slate-900 dark:text-white">FAQ</h2>',
    '<div class="space-y-4">',
    ...t.q.map(x=>`<div><p class="font-semibold">${x[0]}</p><p>${x[1]}</p></div>`),
    '</div></section></div>'
  ].join('');
}

// Helper: generate word counter HTML
function mkWC(t){
  return [
    '<div class="space-y-12 text-slate-700 dark:text-slate-300 not-prose">',
    '<section class="space-y-4">',
    `<h2 class="text-2xl sm:text-3xl font-bold text-slate-900 dark:text-white tracking-tight">${t.h1}</h2>`,
    `<p class="leading-relaxed text-base sm:text-lg">${t.intro}</p>`,
    '<ul class="list-disc pl-5 space-y-1">',
    ...t.ft.map(f=>`<li>${f}</li>`),
    '</ul></section>',
    '<section class="space-y-4">',
    `<h2 class="text-2xl font-bold text-slate-900 dark:text-white">${t.hh}</h2>`,
    '<ol class="list-decimal pl-5 space-y-2">',
    ...t.st.map(s=>`<li>${s}</li>`),
    '</ol></section>',
    '<section class="space-y-4">',
    `<h2 class="text-2xl font-bold text-slate-900 dark:text-white">${t.lh}</h2>`,
    '<div class="overflow-x-auto"><table class="w-full text-sm border-collapse border border-slate-200 dark:border-slate-700">',
    '<thead class="bg-slate-100 dark:bg-slate-800"><tr>',
    `<th class="border p-2 text-left">${t.c1}</th>`,
    `<th class="border p-2 text-left">${t.c2}</th>`,
    '</tr></thead><tbody>',
    ...t.rw.map(r=>`<tr><td class="border p-2">${r[0]}</td><td class="border p-2">${r[1]}</td></tr>`),
    '</tbody></table></div></section>',
    '<section class="space-y-4">',
    '<h2 class="text-2xl font-bold text-slate-900 dark:text-white">FAQ</h2>',
    '<div class="space-y-3">',
    ...t.fq.map(f=>`<div><p class="font-semibold">${f[0]}</p><p>${f[1]}</p></div>`),
    '</div></section></div>'
  ].join('');
}

// ===== PPF CALCULATOR =====
const ppf = rd('ppf-calculator');
const ppfBase = (lang) => [
  `<section class="ppf-content space-y-6">`,
  `<h2>${lang.h}</h2>`,
  `<p>${lang.intro}</p>`,
  `<div class="my-4 rounded-2xl border p-4 space-y-2">`,
  `<p class="font-semibold">${lang.formulaTitle}</p>`,
  `<p class="font-mono bg-slate-100 dark:bg-slate-800 p-2 rounded">M = P x [((1 + i)^n - 1) / i]</p>`,
  `<ul class="list-disc pl-5 space-y-1 text-sm">`,
  `<li><strong>M</strong> = ${lang.m}</li>`,
  `<li><strong>P</strong> = ${lang.p}</li>`,
  `<li><strong>i</strong> = ${lang.i}</li>`,
  `<li><strong>n</strong> = ${lang.nn}</li>`,
  `</ul></div>`,
  `<h2>${lang.rule5Title}</h2><p>${lang.rule5}</p>`,
  `<h2>${lang.extTitle}</h2><p>${lang.ext}</p>`,
  `<h2>${lang.taxTitle}</h2>`,
  `<ul class="list-disc pl-5 space-y-1">`,
  ...lang.tax.map(t=>`<li>${t}</li>`),
  `</ul>`,
  `<h2>${lang.faqTitle}</h2>`,
  `<div class="space-y-4">`,
  ...lang.faqs.map(f=>`<div><p class="font-semibold">${f[0]}</p><p>${f[1]}</p></div>`),
  `</div></section>`
].join('');

const ppfLangs = {
  fr: { h:'Formule de calcul PPF et nuance temporelle', intro:'Le ministere des Finances fixe les taux PPF trimestriellement. Les interets sont calcules <strong>mensuellement</strong> sur le <strong>solde le plus bas entre le 5e et le dernier jour de chaque mois</strong>, credites le 31 mars.', formulaTitle:'Formule PPF :', m:'Valeur de maturite', p:"Montant annuel du depot", i:"Taux d'interet / 100", nn:'Annees (minimum 15)', rule5Title:'Regle du 5 du PPF', rule5:"Investissez avant le 5 de chaque mois pour inclure votre depot dans le calcul des interets. Les depots apres le 5 ne generent pas d'interets pour ce mois.", extTitle:'Extension PPF au-dela de 15 ans', ext:'Apres la periode de blocage, prolongez le compte par blocs de 5 ans avec ou sans nouveaux depots. Le solde existant continue de generer des interets.', taxTitle:'Avantages fiscaux (Section 80C et EEE)', tax:["Depots deductibles jusqu'a Rs 1,5 lakh/an sous Section 80C","Interets accumules entierement exoneres d'impot","Retraits a l'echeance entierement exoneres d'impot"], faqTitle:'Questions frequentes', faqs:[["Depot maximum PPF par an ?","Rs 1,5 lakh par exercice financier (1er avril au 31 mars)."],["Peut-on ouvrir plusieurs comptes PPF ?","Non, une personne ne peut ouvrir qu'un seul compte PPF."],["Retraits partiels autorises ?","Oui, a partir de la 7e annee (max 50% du solde de la 4e annee precedente)."],["Prets contre PPF disponibles ?","Oui, de la 3e a la 6e annee a un taux modere."]] },
  de: { h:'PPF-Zinsberechnungsformel und zeitliche Besonderheit', intro:'Das Finanzministerium legt PPF-Zinssatze vierteljahrlich fest. Zinsen werden <strong>monatlich</strong> auf dem <strong>niedrigsten Saldo zwischen dem 5. und letzten Tag jedes Monats</strong> berechnet, am 31. Marz gutgeschrieben.', formulaTitle:'PPF-Formel:', m:'Falligkeitswert', p:'Jahrliche Einzahlung', i:'Zinssatz / 100', nn:'Jahre (mindestens 15)', rule5Title:'PPF-5er-Regel', rule5:'Investieren Sie vor dem 5. des Monats fur die Zinsberechnung. Einzahlungen nach dem 5. erhalten fur diesen Monat keine Zinsen.', extTitle:'Verlangerung nach 15 Jahren', ext:'Nach der Sperrfrist konnen Sie das Konto in 5-Jahres-Blocken verlangern, mit oder ohne neue Einzahlungen.', taxTitle:'Steuervorteile (Abschnitt 80C und EEE)', tax:['Einzahlungen bis zu Rs 1,5 Lakh/Jahr abzugsfahig gemas Abschnitt 80C','Aufgelaufene Zinsen vollstandig steuerfrei','Falligkeitsauszahlungen vollstandig steuerfrei'], faqTitle:'Haufige Fragen', faqs:[['Maximaler PPF-Einzahlungsbetrag pro Jahr?','Rs 1,5 Lakh pro Geschaftsjahr (1. April bis 31. Marz).'],['Kann man mehrere PPF-Konten eroffnen?','Nein, eine Person kann nur ein PPF-Konto eroffnen.'],['Sind Teilabhebungen erlaubt?','Ja, ab dem 7. Jahr (max. 50% des Saldos vom 4. Vorjahr).'],['Sind Darlehen gegen PPF verfugbar?','Ja, vom 3. bis 6. Jahr zu einem moderaten Zinssatz.']] },
  pt: { h:'Formula de Calculo de Juros do PPF', intro:'O Ministerio das Financas define as taxas PPF trimestralmente. Os juros sao calculados <strong>mensalmente</strong> sobre o <strong>saldo mais baixo entre o 5o e ultimo dia de cada mes</strong>, creditados em 31 de marco.', formulaTitle:'Formula PPF:', m:'Valor de maturidade', p:'Deposito anual', i:'Taxa / 100', nn:'Anos (minimo 15)', rule5Title:'Regra do 5 do PPF', rule5:'Invista antes do dia 5 de cada mes para garantir que o deposito seja incluido no calculo de juros daquele mes.', extTitle:'Extensao apos 15 anos', ext:'Apos o bloqueio de 15 anos, estenda a conta em blocos de 5 anos. O saldo existente continua a render juros.', taxTitle:'Beneficios Fiscais (Secao 80C e EEE)', tax:['Depositos dedutiveis ate Rs 1,5 lakh/ano pela Secao 80C','Juros acumulados totalmente isentos de impostos','Saques no vencimento totalmente isentos de impostos'], faqTitle:'Perguntas Frequentes', faqs:[['Valor maximo de deposito PPF anual?','Rs 1,5 lakh por exercicio financeiro (1o de abril a 31 de marco).'],[`E possivel abrir varias contas PPF?`,'Nao, apenas uma conta por pessoa.'],['Saques parciais sao permitidos?','Sim, a partir do 7o ano (maximo 50% do saldo do 4o ano anterior).'],['Emprestimos contra PPF estao disponiveis?','Sim, do 3o ao 6o ano a uma taxa moderada.']] },
  it: { h:"Formula di Calcolo degli Interessi PPF", intro:"Il Ministero delle Finanze stabilisce i tassi PPF trimestralmente. Gli interessi vengono calcolati <strong>mensilmente</strong> sul <strong>saldo piu basso tra il 5 e l'ultimo giorno di ogni mese</strong> e accreditati il 31 marzo.", formulaTitle:'Formula PPF:', m:'Valore alla scadenza', p:'Deposito annuale', i:'Tasso / 100', nn:'Anni (minimo 15)', rule5Title:'Regola del 5 del PPF', rule5:'Investi prima del 5 di ogni mese affinche il deposito sia incluso nel calcolo degli interessi. I depositi dopo il 5 non generano interessi per quel mese.', extTitle:'Estensione oltre 15 anni', ext:'Dopo il blocco di 15 anni, estendi il conto in blocchi di 5 anni con o senza nuovi versamenti.', taxTitle:'Vantaggi Fiscali (Sezione 80C e EEE)', tax:['Depositi deducibili fino a Rs 1,5 lakh/anno ai sensi della Sezione 80C','Interessi maturati completamente esenti da imposte','Prelievi alla scadenza completamente esenti da imposte'], faqTitle:'Domande Frequenti', faqs:[["Importo massimo del deposito PPF annuo?","Rs 1,5 lakh per esercizio finanziario (1 aprile - 31 marzo)."],["E possibile aprire piu conti PPF?","No, solo un conto per persona."],["Sono consentiti prelievi parziali?","Si, dal 7 anno (max 50% del saldo del 4 anno precedente)."],["Sono disponibili prestiti contro PPF?","Si, dal 3 al 6 anno a un tasso moderato."]] },
  ja: { h:'PPF利子計算式と時期のポイント', intro:'財務省はPPFの利率を四半期ごとに設定します。利子は各月の<strong>5日目終値と末日の最低残高</strong>に対して<strong>毎月</strong>計算され、3月31日に積み立てられます。', formulaTitle:'PPF計算式：', m:'満期金額', p:'年間預入金額', i:'利率 / 100', nn:'年数（最低15年）', rule5Title:'PPFの5日ルール', rule5:'毎月5日より前に投資することで、その月の利子計算に預金が含まれます。5日以降の預金はその月の利子を得られません。', extTitle:'15年後のPPF延長', ext:'最初の15年ロック期間後、PPF口座を5年単位で延長できます。新規預金ありまたはなしを選択できます。', taxTitle:'PPFの税制優遇（セクション80CとEEEステータス）', tax:['年間Rs 1.5ラクまでセクション80Cで控除可能','積み立てられた利子は完全に非課税','満期引き出しは完全に非課税'], faqTitle:'よくある質問', faqs:[['年間最大預入額は？','会計年度（4月1日〜3月31日）ごとにRs 1.5ラクです。'],['複数口座開設できますか？','いいえ、一人は一つのみ開設できます。'],['部分引き出しは可能？','7年目から4年前の残高の最大50%まで可能です。'],['PPFに対するローンは？','3年目から6年目の間に適度な利率で利用できます。']] },
  ko: { h:'PPF 이자 계산 공식 및 시기 세부사항', intro:'재무부는 PPF 이자율을 분기별로 설정합니다. 이자는 각 달력월의 <strong>5일 종가와 마지막 날 사이의 최저 잔액</strong>에 대해 <strong>매월</strong> 계산되며 매년 3월 31일에 적립됩니다.', formulaTitle:'PPF 공식:', m:'만기 금액', p:'연간 예치 금액', i:'이자율 / 100', nn:'연수 (최소 15년)', rule5Title:'PPF 5일 규칙', rule5:'매월 5일 이전에 투자하여 해당 월의 이자 계산에 예금이 포함되도록 하세요. 5일 이후 예금은 해당 월 이자를 받지 못합니다.', extTitle:'15년 이후 PPF 연장', ext:'초기 15년 잠금 기간 후 PPF 계좌를 5년 단위로 연장할 수 있습니다. 신규 납입 여부를 선택할 수 있습니다.', taxTitle:'PPF 세금 혜택 (섹션 80C와 EEE)', tax:['연간 Rs 1.5 라크까지 섹션 80C에서 공제 가능','적립된 이자는 완전히 비과세','만기 인출은 완전히 비과세'], faqTitle:'자주 묻는 질문', faqs:[['PPF 연간 최대 예치 금액은?','회계연도(4월 1일~3월 31일)당 Rs 1.5 라크입니다.'],['여러 PPF 계좌를 개설할 수 있습니까?','아니요, 한 사람은 하나만 개설 가능합니다.'],['부분 인출이 가능합니까?','네, 7년차부터 4년 전 잔액의 최대 50%까지 가능합니다.'],['PPF에 대한 대출이 가능합니까?','네, 3년차부터 6년차 사이에 적당한 이자율로 이용 가능합니다.']] }
};
for(const[l,t] of Object.entries(ppfLangs)){const h=ppfBase(t);if(fix(ppf,l,h)){n++;console.log('PPF '+l+' -> '+h.length);}}
wr('ppf-calculator',ppf);

// ===== SWP CALCULATOR =====
const swp = rd('swp-calculator');
const swpLangs = {
  fr: { h:"Qu'est-ce qu'un Plan de Retrait Systematique (SWP) ?", what:"Un Plan de Retrait Systematique (SWP) permet aux investisseurs de retirer une somme predeterminee a intervalles reguliers de leur corpus accumulé, tout en gardant le solde investi pour generer des rendements composes.", formulaLabel:"Formule SWP", formulaCode:"Corpus mensuel = Corpus precedent x (1 + r/12) - Retrait mensuel", formulaNote:"r = taux de rendement annuel", taxH:"Avantages fiscaux du SWP", taxP:"Le SWP est fiscalement efficace. Chaque retrait comprend le remboursement du principal (non imposable) et les gains en capital (imposables). Seule la composante gain est imposable.", faqs:[["Le SWP est-il meilleur que l'option dividende?","Oui, car seul le gain est imposable dans le SWP."],["Montant minimum SWP?","La plupart des fonds permettent Rs 500/mois minimum."],["Peut-on modifier le SWP?","Oui, les SWP peuvent etre modifies ou arretes a tout moment avec un preavis minimal."],["SWP et retraite?","Le SWP est une excellente strategie de revenus a la retraite avec un flux regulier."]] },
  de: { h:"Was ist ein Systematischer Auszahlungsplan (SWP)?", what:"Ein Systematischer Auszahlungsplan (SWP) ermoglicht Investmentfonds-Anlegern, in regelmasigen Abstanden einen vorher festgelegten Betrag abzuheben, wahrend der verbleibende Saldo investiert bleibt, um Zinseszinsen zu generieren.", formulaLabel:"SWP-Formel", formulaCode:"Monatliches Kapital = Vorheriges Kapital x (1 + r/12) - Monatliche Auszahlung", formulaNote:"r = jahrliche Rendite", taxH:"Steuervorteile des SWP", taxP:"SWP ist steuerlich effizient, da jede Auszahlung zwei Komponenten enthalt: Kapitalruckzahlung (nicht steuerpflichtig) und Kapitalgewinne (steuerpflichtig). Nur die Gewinnkomponente wird besteuert.", faqs:[["Ist SWP besser als die Dividendenoption?","Ja, da nur der Gewinn steuerpflichtig ist."],["Mindest-SWP-Betrag?","Die meisten Fonds erlauben ab Rs 500/Monat."],["Kann man einen SWP andern oder stoppen?","Ja, SWPs konnen jederzeit mit minimaler Vorankundigung geandert werden."],["SWP und Rente?","SWP ist eine ausgezeichnete Einkommensstrategie mit regelmasigem Geldfluss."]] },
  it: { h:"Cos'e un Piano di Prelievo Sistematico (SWP)?", what:"Un Piano di Prelievo Sistematico (SWP) consente agli investitori di prelevare una somma predeterminata a intervalli regolari dal corpus accumulato, mantenendo il saldo investito per generare rendimenti composti.", formulaLabel:"Formula SWP", formulaCode:"Corpus mensile = Corpus precedente x (1 + r/12) - Prelievo mensile", formulaNote:"r = rendimento annuale", taxH:"Vantaggi Fiscali del SWP", taxP:"Il SWP e fiscalmente efficiente. Ogni prelievo include il rimborso del capitale (non tassabile) e i guadagni in conto capitale (tassabili). Solo la componente del guadagno e tassabile.", faqs:[["Il SWP e migliore dell'opzione dividendo?","Si, perche solo il guadagno e tassabile nel SWP."],["Importo minimo SWP?","La maggior parte dei fondi consente Rs 500/mese minimo."],["E possibile modificare o interrompere un SWP?","Si, i SWP possono essere modificati o interrotti in qualsiasi momento."],["SWP e pensione?","Il SWP e un'ottima strategia di reddito pensionistico con flusso regolare."]] }
};
for(const[l,t] of Object.entries(swpLangs)){
  const html=[`<section class="swp-content space-y-6"><h2>${t.h}</h2><p>${t.what}</p>`,`<h2>${t.formulaLabel}</h2><div class="my-4 rounded-2xl border p-4"><p class="font-mono bg-slate-100 dark:bg-slate-800 p-2 rounded">${t.formulaCode}</p><p class="text-xs text-slate-500 mt-1">${t.formulaNote}</p></div>`,`<h2>${t.taxH}</h2><p>${t.taxP}</p><h2>FAQ</h2><div class="space-y-4">`,t.faqs.map(f=>`<div><p class="font-semibold">${f[0]}</p><p>${f[1]}</p></div>`).join(''),'</div></section>'].join('');
  if(fix(swp,l,html)){n++;console.log('SWP '+l+' -> '+html.length);}
}
wr('swp-calculator',swp);

// ===== AGE CALCULATOR =====
const age = rd('age-calculator');
const ageLangs = {
  fr: { h:"Calculateur d'age - Calculez votre age exact en ligne", intro:"Notre calculateur d'age calcule votre age exact en annees, mois et jours. Il prend en compte les annees bissextiles et toutes les regles du calendrier gregorien.", h2:"Comment ca marche", steps:["Entrez votre date de naissance","Selectionnez la date cible","Obtenez votre age exact en annees, mois et jours","Consultez les jours jusqu'au prochain anniversaire"], h3:"Utilisations courantes", uses:["Verification d'admissibilite pour les examens et les emplois","Calculs medicaux et calendriers de vaccination","Verifications legales pour les contrats et le vote","Planification de la retraite","Astrologie et numerologie"], faqs:[["Le calculateur prend-il en compte les annees bissextiles?","Oui, notre calculateur gere correctement les annees bissextiles et les personnes nees le 29 fevrier."],["Puis-je calculer mon age a une date future?","Oui, selectionnez simplement une date future dans le champ de date cible."],["Quelle est la precision?","Le calculateur est precis au jour pres."],["Comment l'age est-il calcule dans differents pays?","Le systeme occidental compte les annees completes depuis la naissance. Certaines cultures asiatiques comptent la grossesse et considerent un bebe comme ayant 1 an a la naissance."]] },
  de: { h:"Altersrechner - Berechnen Sie Ihr genaues Alter online", intro:"Unser Altersrechner berechnet Ihr genaues Alter in Jahren, Monaten und Tagen unter Berucksichtigung von Schaltjahren und allen Regeln des Gregorianischen Kalenders.", h2:"Wie es funktioniert", steps:["Geben Sie Ihr Geburtsdatum ein","Wahlen Sie das Zieldatum (Standard: heute)","Erhalten Sie Ihr genaues Alter in Jahren, Monaten und Tagen","Sehen Sie die Tage bis zum nachsten Geburtstag"], h3:"Anwendungsfalle", uses:["Berechtigungsprufung fur Prufungen und Stellen","Medizinische Berechnungen und Impfplane","Rechtliche Altersverifizierungen","Rentenplanung","Astrologie und Numerologie"], faqs:[["Berucksichtigt der Rechner Schaltjahre?","Ja, unser Rechner behandelt Schaltjahre korrekt und Personen, die am 29. Februar geboren wurden."],["Kann ich mein Alter an einem zukunftigen Datum berechnen?","Ja, wahlen Sie einfach ein zukunftiges Datum im Zieldatumsfeld aus."],["Wie genau ist der Rechner?","Der Rechner ist auf den Tag genau."],["Wie wird Alter in verschiedenen Landern berechnet?","Das westliche System zahlt vollstandige Jahre seit der Geburt. Einige asiatische Kulturen zahlen die Schwangerschaft und betrachten ein Baby bei der Geburt als 1 Jahr alt."]] },
  pt: { h:"Calculadora de Idade - Calcule sua Idade Exata Online", intro:"Nossa calculadora de idade calcula sua idade exata em anos, meses e dias, levando em conta anos bissextos e as regras do calendario gregoriano.", h2:"Como funciona", steps:["Digite sua data de nascimento","Selecione a data alvo (padrao: hoje)","Obtenha sua idade exata em anos, meses e dias","Veja os dias ate o proximo aniversario"], h3:"Casos de uso", uses:["Verificacao de elegibilidade para exames e empregos","Calculos medicos e calendarios de vacinacao","Verificacoes legais de idade para contratos e votacao","Planejamento de aposentadoria","Astrologia e numerologia"], faqs:[["A calculadora considera anos bissextos?","Sim, nossa calculadora lida corretamente com anos bissextos e pessoas nascidas em 29 de fevereiro."],["Posso calcular minha idade em uma data futura?","Sim, basta selecionar uma data futura no campo de data alvo."],["Qual e a precisao?","A calculadora e precisa ao dia."],["Como a idade e calculada em diferentes paises?","O sistema ocidental conta os anos completos desde o nascimento. Algumas culturas asiaticas contam a gravidez e consideram um bebe com 1 ano ao nascer."]] },
  it: { h:"Calcolatore dell'Eta - Calcola la tua Eta Esatta Online", intro:"Il nostro calcolatore dell'eta calcola la tua eta esatta in anni, mesi e giorni, tenendo conto degli anni bisestili e di tutte le regole del calendario gregoriano.", h2:"Come funziona", steps:["Inserisci la tua data di nascita","Seleziona la data di destinazione (predefinita: oggi)","Ottieni la tua eta esatta in anni, mesi e giorni","Guarda i giorni fino al prossimo compleanno"], h3:"Casi d'uso", uses:["Verifica dell'ammissibilita agli esami e ai lavori","Calcoli medici e calendari vaccinali","Verifiche legali dell'eta per contratti e voto","Pianificazione pensionistica","Astrologia e numerologia"], faqs:[["Il calcolatore considera gli anni bisestili?","Si, il nostro calcolatore gestisce correttamente gli anni bisestili e le persone nate il 29 febbraio."],["Posso calcolare la mia eta in una data futura?","Si, seleziona semplicemente una data futura nel campo della data di destinazione."],["Quanto e preciso?","Il calcolatore e preciso al giorno."],["Come viene calcolata l'eta in diversi paesi?","Il sistema occidentale conta gli anni completi dalla nascita. Alcune culture asiatiche contano la gravidanza e considerano un neonato di 1 anno alla nascita."]] },
  ja: { h:"年齢計算機 - 正確な年齢をオンラインで計算", intro:"私たちの年齢計算機は、グレゴリオ暦のルールとうるう年を考慮して、あなたの正確な年齢を年、月、日で計算します。", h2:"年齢計算機の仕組み", steps:["生年月日を入力する","目標日を選択する（デフォルト：今日）","年、月、日での正確な年齢を取得する","次の誕生日までの日数を確認する"], h3:"主な用途", uses:["試験や職業の資格確認","医療計算と予防接種スケジュール","契約や投票のための法的年齢確認","退職計画","占星術と数秘術"], faqs:[["計算機はうるう年を考慮しますか？","はい、うるう年と2月29日生まれの方を正しく処理します。"],["将来の日付での年齢を計算できますか？","はい、目標日フィールドで将来の日付を選択するだけです。"],["精度は？","計算機は日単位で正確です。"],["異なる国での年齢の計算方法は？","西洋システムは誕生からの完全な年数を数えます。一部のアジアの文化では妊娠を数え、赤ちゃんを生まれた時に1歳と考えます。"]] },
  ko: { h:"나이 계산기 - 정확한 나이를 온라인으로 계산하세요", intro:"저희 나이 계산기는 그레고리력 규칙과 윤년을 고려하여 연, 월, 일로 정확한 나이를 계산합니다.", h2:"나이 계산기 작동 방법", steps:["생년월일을 입력하세요","목표 날짜를 선택하세요 (기본값: 오늘)","연, 월, 일로 정확한 나이를 확인하세요","다음 생일까지 남은 날을 확인하세요"], h3:"사용 사례", uses:["시험 및 직업의 나이 자격 확인","의료 계산 및 예방 접종 일정","계약, 투표를 위한 법적 나이 확인","은퇴 계획","점성술과 수비학"], faqs:[["계산기가 윤년을 고려하나요?","네, 윤년과 2월 29일에 태어난 사람들을 올바르게 처리합니다."],["미래 날짜의 나이를 계산할 수 있나요?","네, 목표 날짜 필드에서 미래 날짜를 선택하면 됩니다."],["정확도는?","일 단위로 정확합니다."],["다른 나라에서 나이를 계산하는 방법은?","서양 시스템은 출생 이후의 완전한 연도를 셉니다. 일부 아시아 문화에서는 임신을 세고 아기가 태어났을 때 1살이라고 간주합니다."]] }
};
for(const[l,t] of Object.entries(ageLangs)){
  const html=[`<section class="age-content space-y-6"><h2>${t.h}</h2><p>${t.intro}</p>`,`<h2>${t.h2}</h2><ol class="list-decimal pl-5 space-y-1">${t.steps.map(s=>`<li>${s}</li>`).join('')}</ol>`,`<h2>${t.h3}</h2><ul class="list-disc pl-5 space-y-1">${t.uses.map(u=>`<li>${u}</li>`).join('')}</ul>`,`<h2>FAQ</h2><div class="space-y-4">${t.faqs.map(f=>`<div><p class="font-semibold">${f[0]}</p><p>${f[1]}</p></div>`).join('')}</div></section>`].join('');
  if(fix(age,l,html)){n++;console.log('Age '+l+' -> '+html.length);}
}
wr('age-calculator',age);

// ===== GRATUITY CALCULATOR =====
const grat = rd('gratuity-calculator');
const gratHi = [
  '<section class="gratuity-content space-y-6">',
  '<h2>Gratuity Ganana ki Poori Guide</h2>',
  '<p>Gratuity ek vadhaanik monetary labh hai jo niyoktaon dwara dirghakalik, nirantar seva ko puraskar dene ke liye dey hai. Yah tab milti hai jab karmachari isteefa deta hai, sevaanivratt hota hai, ya mrityu/apangata ke mamale mein.</p>',
  '<h2>Gratuity Sutra</h2>',
  '<div class="my-4 rounded-2xl border p-4">',
  '<p class="font-semibold">Gratuity Adhiniyam ke tahat covered employees ke liye:</p>',
  '<p class="font-mono bg-slate-100 dark:bg-slate-800 p-2 rounded">Gratuity = (Antim Vetan x 15 x Seva Varsh) / 26</p>',
  '<p class="font-semibold mt-2">Gratuity Adhiniyam ke bahar non-covered employees ke liye:</p>',
  '<p class="font-mono bg-slate-100 dark:bg-slate-800 p-2 rounded">Gratuity = (Antim Vetan x 15 x Seva Varsh) / 30</p>',
  '</div>',
  '<h2>Patrata Niyam</h2>',
  '<ul class="list-disc pl-5 space-y-1">',
  '<li>Kam se kam 5 saal ki nirantar seva jaruri hai (mrityu/apangata ko chhodkar)</li>',
  '<li>10 ya adhik karmachariyon wale pratishthan Gratuity Adhiniyam ke antargat aate hain</li>',
  '<li>Adhikatam gratuity Rs 20 lakh tak seemit hai</li>',
  '<li>6 mahine se adhik seva ko poorn varsh mana jata hai</li>',
  '</ul>',
  '<h2>Gratuity par Kar</h2>',
  '<p>Sarkari karmacharion ke liye gratuity poori tarah kar mukt hai. Niji kshetra ke liye, nyunatam rashi kar mukt hai: vastav mein prapt gratuity, Rs 20 lakh, ya 15 x antim vetan x seva varsh / 26.</p>',
  '<h2>Aksar Puche Jane Wale Prashn</h2>',
  '<div class="space-y-4">',
  '<div><p class="font-semibold">Kya gratuity 5 saal se pahle mil sakti hai?</p><p>Samanyatah nahin. Mrityu ya sthayi apangata ke mamale mein haan.</p></div>',
  '<div><p class="font-semibold">Gratuity mein antim vetan kya hai?</p><p>Mool vetan aur mahangai bhatta (DA). HRA, bonus aur anya bhatte shamil nahin hain.</p></div>',
  '<div><p class="font-semibold">Gratuity kab bhugataan ki jani chahiye?</p><p>Seva samapti ke 30 dinon ke andar.</p></div>',
  '<div><p class="font-semibold">Gratuity ki adhikatam seema kya hai?</p><p>Gratuity Adhiniyam ke tahat Rs 20 lakh.</p></div>',
  '</div></section>'
].join('');
const gratEs = [
  '<section class="gratuity-content space-y-6">',
  '<h2>Guia Completa para el Calculo de Gratificacion</h2>',
  '<p>La gratificacion es un beneficio monetario legal pagadero por los empleadores para recompensar el servicio continuo y prolongado al momento de renuncia, jubilacion, o en casos de muerte o discapacidad permanente.</p>',
  '<h2>Formula de Gratificacion</h2>',
  '<div class="my-4 rounded-2xl border p-4">',
  '<p class="font-semibold">Para empleados cubiertos por la Ley de Gratificacion:</p>',
  '<p class="font-mono bg-slate-100 dark:bg-slate-800 p-2 rounded">Gratificacion = (Ultimo salario x 15 x Anos de servicio) / 26</p>',
  '<p class="font-semibold mt-2">Para empleados no cubiertos por la Ley:</p>',
  '<p class="font-mono bg-slate-100 dark:bg-slate-800 p-2 rounded">Gratificacion = (Ultimo salario x 15 x Anos de servicio) / 30</p>',
  '</div>',
  '<h2>Reglas de Elegibilidad</h2>',
  '<ul class="list-disc pl-5 space-y-1">',
  '<li>Minimo 5 anos de servicio continuo requerido (excepto en caso de muerte/discapacidad)</li>',
  '<li>Establecimientos con 10 o mas empleados quedan bajo la Ley de Gratificacion</li>',
  '<li>Gratificacion maxima limitada a Rs 20 lakh bajo la Ley</li>',
  '<li>Mas de 6 meses de servicio se cuenta como un ano completo</li>',
  '</ul>',
  '<h2>Impuesto sobre la Gratificacion</h2>',
  '<p>Completamente libre de impuestos para empleados gubernamentales. Para el sector privado, el minimo de los siguientes esta libre de impuestos: la gratificacion real recibida, Rs 20 lakh, o 15 x ultimo salario x anos de servicio / 26.</p>',
  '<h2>Preguntas Frecuentes</h2>',
  '<div class="space-y-4">',
  '<div><p class="font-semibold">Se puede obtener gratificacion antes de 5 anos?</p><p>Generalmente no, excepto en caso de muerte o discapacidad permanente.</p></div>',
  '<div><p class="font-semibold">Que se incluye en el ultimo salario?</p><p>Salario base y asignacion de carestia (DA). No se incluyen HRA, bonificaciones ni otras asignaciones.</p></div>',
  '<div><p class="font-semibold">Cuando debe pagarse la gratificacion?</p><p>Dentro de los 30 dias posteriores a la terminacion del servicio.</p></div>',
  '<div><p class="font-semibold">Cual es el limite maximo de gratificacion?</p><p>Rs 20 lakh bajo la Ley de Gratificacion de la Pago (Payment of Gratuity Act).</p></div>',
  '</div></section>'
].join('');
if(fix(grat,'hi',gratHi)){n++;console.log('Gratuity hi fixed');}
if(fix(grat,'es',gratEs)){n++;console.log('Gratuity es fixed');}
wr('gratuity-calculator',grat);

// ===== XIRR CALCULATOR =====
const xirr = rd('xirr-calculator');
const xirrTable = '<div class="overflow-x-auto my-4"><table class="w-full text-left text-sm border-collapse border border-slate-200 dark:border-slate-700"><thead class="bg-slate-100 dark:bg-slate-800"><tr><th class="border p-2">Metrique</th><th class="border p-2">Flux irreguliers</th><th class="border p-2">Meilleur usage</th></tr></thead><tbody><tr><td class="border p-2">XIRR</td><td class="border p-2">Oui</td><td class="border p-2">SIP, investissements irreguliers</td></tr><tr><td class="border p-2">IRR</td><td class="border p-2">Non</td><td class="border p-2">Flux a intervalles egaux</td></tr><tr><td class="border p-2">CAGR</td><td class="border p-2">Non</td><td class="border p-2">Investissement unique</td></tr></tbody></table></div>';
const xirrHiTable = '<div class="overflow-x-auto my-4"><table class="w-full text-left text-sm border-collapse border border-slate-200 dark:border-slate-700"><thead class="bg-slate-100 dark:bg-slate-800"><tr><th class="border p-2">Metric</th><th class="border p-2">Aniyamit Nakadi Pravaah</th><th class="border p-2">Sarvottam Upyog</th></tr></thead><tbody><tr><td class="border p-2">XIRR</td><td class="border p-2">Haan</td><td class="border p-2">SIP, aniyamit nivesh</td></tr><tr><td class="border p-2">IRR</td><td class="border p-2">Nahin</td><td class="border p-2">Saman antar nakadi pravaah</td></tr><tr><td class="border p-2">CAGR</td><td class="border p-2">Nahin</td><td class="border p-2">Ekal nivesh</td></tr></tbody></table></div>';
const xirrHi = ['<section class="xirr-content space-y-6">','<h2>XIRR ko Samajhna: Extended Internal Rate of Return</h2>','<p>XIRR (Extended Internal Rate of Return) aniyamit ya aavarti calendar taarikhon par hone wale kaii nakadi antarvaah aur bahirvaah wale nivesthanon par vaarshikrit return ki ganana karne ka vaishvik suvarna maanak hai.</p>',xirrHiTable,'<h2>XIRR Sutra</h2>','<div class="my-4 rounded-2xl border p-4"><p class="font-mono bg-slate-100 dark:bg-slate-800 p-2 rounded">NPV = Sum [Ci / (1+r)^(di/365)] = 0</p><p class="text-xs text-slate-500 mt-1">Jahan Ci = i-vaan nakadi pravaah, di = pahli taareekh se din</p></div>','<h2>Vastavik Duniya ke Upyog ke Maale</h2>','<ul class="list-disc pl-5 space-y-1"><li>Mutual Fund SIP ke liye vastavik return ki ganana karein</li><li>Kayi khareed/bikri taarikhon wale portfolios ka mulyankan karein</li><li>Achal sampatti mein kiraya aay sahit return maapain</li><li>ULIP ya endowment yojanaon ki vastavik dar maapain</li></ul>','<h2>Aksar Puche Jane Wale Prashn</h2>','<div class="space-y-4">','<div><p class="font-semibold">Excel mein XIRR kaise calculate karein?</p><p>=XIRR(values, dates) function upyog karein jahan values nakadi pravaah ki shreni hai aur dates sambandhi taarikhain hain.</p></div>','<div><p class="font-semibold">SIP ke liye accha XIRR kya hai?</p><p>Equity funds ke liye 12-15% XIRR samanyatah accha mana jata hai. Debt funds ke liye, 7-9% uchit hai.</p></div>','<div><p class="font-semibold">XIRR negative kyun ho sakta hai?</p><p>Negative XIRR batata hai ki nivesh ne mulya khoya hai. Yah market correction ya kharab performance wale fund ke liye ho sakta hai.</p></div>','<div><p class="font-semibold">XIRR vs CAGR?</p><p>XIRR aniyamit nakadi pravaah sambhalta hai; CAGR ekal nivesh ke liye ek seedha antar maap karta hai.</p></div>','</div></section>'].join('');
const xirrFr = ['<section class="xirr-content space-y-6">','<h2>Comprendre le XIRR : Taux de Rendement Interne Etendu</h2>','<p>Le XIRR (Extended Internal Rate of Return) est la reference mondiale pour calculer les rendements annualises sur les investissements impliquant de multiples entrees et sorties de tresorerie a des dates irregulieres ou recurrentes.</p>',xirrTable,'<h2>Formule XIRR</h2>','<div class="my-4 rounded-2xl border p-4"><p class="font-mono bg-slate-100 dark:bg-slate-800 p-2 rounded">VAN = Sum [Ci / (1+r)^(di/365)] = 0</p><p class="text-xs text-slate-500 mt-1">Ci = flux de tresorerie, di = jours depuis la premiere date</p></div>','<h2>Cas d\'utilisation reels</h2>','<ul class="list-disc pl-5 space-y-1"><li>SIP de fonds communs de placement a differentes valeurs liquidatives</li><li>Portefeuilles boursiers avec plusieurs dates d\'achat/vente</li><li>Immobilier avec revenus locatifs et plus-values</li><li>ULIP et plans de dotation avec primes irregulieres</li></ul>','<h2>FAQ</h2>','<div class="space-y-4">','<div><p class="font-semibold">Comment calculer XIRR dans Excel ?</p><p>Utilisez la fonction =XIRR(valeurs, dates) dans Excel ou valeurs est une plage de flux de tresorerie et dates sont les dates correspondantes.</p></div>','<div><p class="font-semibold">Qu\'est-ce qu\'un bon XIRR pour un SIP ?</p><p>Pour les fonds d\'actions, un XIRR de 12-15% est generalement considere comme bon. Pour les fonds obligataires, 7-9% est raisonnable.</p></div>','<div><p class="font-semibold">Pourquoi le XIRR peut-il etre negatif ?</p><p>Un XIRR negatif indique que l\'investissement a perdu de la valeur due a des corrections de marche.</p></div>','<div><p class="font-semibold">XIRR vs CAGR ?</p><p>XIRR gere les flux irreguliers; CAGR suppose un seul investissement initial.</p></div>','</div></section>'].join('');
if(fix(xirr,'hi',xirrHi)){n++;console.log('XIRR hi fixed');}
if(fix(xirr,'fr',xirrFr)){n++;console.log('XIRR fr fixed');}
wr('xirr-calculator',xirr);

// ===== WORD COUNTER =====
const wc = rd('word-counter');
const wcLangs = {
  fr: { h1:'Compteur de Mots en Ligne', intro:"Notre compteur de mots fournit des metriques completes en temps reel : mots, caracteres, phrases, paragraphes et temps de lecture estime. Que vous redigiez une these universitaire, polissiez un article ou prepariez un discours, notre outil vous aide.", ft:["Comptage en temps reel pendant la frappe","Mots et caracteres (avec/sans espaces)","Phrases et paragraphes","Temps de lecture et de discours estime","Densite de mots-cles pour le referencement"], hh:'Comment utiliser le Compteur', st:["Collez ou tapez votre texte dans la zone de texte","Les metriques sont calculees instantanement","Consultez les statistiques en bas du texte"], lh:'Limites de mots courantes', c1:'Type de document', c2:'Plage typique', rw:[["Article de blog","800-2 000 mots"],["Article academique","3 000-8 000 mots"],["Roman","80 000-100 000 mots"],["Tweet","Jusqu'a 280 caracteres"]], fq:[["Comment les mots sont-ils comptes?","Les mots sont definis comme des sequences de caracteres non blancs separes par des espaces ou des sauts de ligne."],["Les caracteres incluent-ils les espaces?","Nous affichons les deux metriques : caracteres avec espaces et caracteres sans espaces."],["Comment est calcule le temps de lecture?","En supposant une vitesse de lecture moyenne de 200-250 mots par minute pour les adultes."]] },
  de: { h1:'Online Worter Zahlen', intro:'Unser Worterzahler liefert Echtzeit-Metriken : Worter, Zeichen, Satze, Absatze und geschatzte Lesezeit. Ob Sie eine Universitatsarbeit verfassen, einen Artikel polieren oder eine Rede vorbereiten, unser Tool hilft.', ft:['Echtzeit-Zahlung beim Tippen','Worter und Zeichen (mit/ohne Leerzeichen)','Satze und Absatze','Geschatzte Lese- und Redezeit','Keyword-Dichte fur SEO'], hh:'Verwendung des Worterzahlers', st:['Text in das Textfeld einfugen oder eingeben','Metriken werden sofort berechnet','Statistiken unten im Text uberprufen'], lh:'Haufige Wortlimits', c1:'Dokumenttyp', c2:'Typischer Bereich', rw:[['Blog-Artikel','800-2.000 Worter'],['Akademische Arbeit','3.000-8.000 Worter'],['Roman','80.000-100.000 Worter'],['Tweet','Bis zu 280 Zeichen']], fq:[['Wie werden Worter gezahlt?','Worter sind Nicht-Leerzeichen-Sequenzen, durch Leerzeichen oder Zeilenumbr. getrennt.'],['Zeichen mit oder ohne Leerzeichen?','Beide Metriken werden angezeigt.'],['Wie wird Lesezeit berechnet?','Basierend auf einer durchschnittlichen Leserate von 200-250 Wortern pro Minute fur Erwachsene.']] },
  pt: { h1:'Contador de Palavras Online', intro:'Nosso contador de palavras fornece metricas em tempo real : palavras, caracteres, frases, paragrafos e tempo de leitura estimado. Seja redigindo uma tese universitaria, polindo um artigo ou preparando um discurso, nosso ferramenta ajuda.', ft:['Contagem em tempo real durante a digitacao','Palavras e caracteres (com/sem espacos)','Frases e paragrafos','Tempo de leitura e discurso estimado','Densidade de palavras-chave para SEO'], hh:'Como usar o Contador de Palavras', st:['Cole ou digite seu texto na caixa de texto','As metricas sao calculadas instantaneamente','Veja as estatisticas abaixo do texto'], lh:'Limites comuns de palavras', c1:'Tipo de documento', c2:'Intervalo tipico', rw:[['Artigo de blog','800-2.000 palavras'],['Artigo academico','3.000-8.000 palavras'],['Romance','80.000-100.000 palavras'],['Tweet','Ate 280 caracteres']], fq:[['Como as palavras sao contadas?','Palavras sao sequencias de caracteres nao-brancos separadas por espacos ou quebras de linha.'],['Os caracteres incluem espacos?','Sim, ambas as metricas sao exibidas.'],['Como o tempo de leitura e calculado?','Assumindo uma velocidade de leitura media de 200-250 palavras por minuto para adultos.']] },
  it: { h1:'Contatore di Parole Online', intro:"Il nostro contatore di parole fornisce metriche in tempo reale : parole, caratteri, frasi, paragrafi e tempo di lettura stimato. Che tu stia redigendo una tesi universitaria, rifinendo un articolo o preparando un discorso, il nostro strumento ti aiuta.", ft:["Conteggio in tempo reale durante la digitazione","Parole e caratteri (con/senza spazi)","Frasi e paragrafi","Tempo di lettura e discorso stimato","Densita delle parole chiave per il SEO"], hh:'Come usare il Contatore di Parole', st:["Incolla o digita il tuo testo nella casella di testo","Le metriche vengono calcolate istantaneamente","Controlla le statistiche in basso"], lh:'Limiti di parole comuni', c1:'Tipo di documento', c2:'Intervallo tipico', rw:[['Articolo di blog','800-2.000 parole'],['Articolo accademico','3.000-8.000 parole'],['Romanzo','80.000-100.000 parole'],['Tweet','Fino a 280 caratteri']], fq:[['Come vengono contate le parole?','Le parole sono sequenze di caratteri non-spazio separate da spazi o interruzioni di riga.'],["I caratteri includono gli spazi?","Si, entrambe le metriche sono mostrate."],["Come viene calcolato il tempo di lettura?","Assumendo una velocita di lettura media di 200-250 parole al minuto per gli adulti."]] },
  ja: { h1:'オンライン文字数カウント', intro:'文字カウンターはリアルタイムで単語数、文字数、文数、段落数、推定読み時間を提供します。大学論文を書いたり、記事を磨いたり、スピーチを準備する際にも活用できます。', ft:['入力中のリアルタイムカウント','単語数と文字数（スペースあり/なし）','文数と段落数','推定読み時間とスピーチ時間','SEOのためのキーワード密度'], hh:'文字カウンターの使い方', st:['テキストをテキストボックスに貼り付けるか入力する','メトリクスが即座に計算される','テキスト下の統計を確認する'], lh:'一般的な文字数制限', c1:'文書タイプ', c2:'典型的な範囲', rw:[['ブログ記事','800〜2,000語'],['学術論文','3,000〜8,000語'],['小説','80,000〜100,000語'],['ツイート','280文字まで']], fq:[['単語はどのようにカウントされますか？','単語はスペースや改行で区切られた非空白文字の連続として定義されます。'],['文字数にはスペースが含まれますか？','スペースありとスペースなし、両方のメトリクスを表示します。'],['読み時間はどのように計算されますか？','成人の平均読み速度200〜250語/分を仮定して計算します。']] },
  ko: { h1:'온라인 단어 카운터', intro:'단어 카운터는 실시간으로 단어 수, 문자 수, 문장 수, 단락 수, 예상 읽기 시간을 제공합니다. 대학 논문을 작성하거나, 기사를 다듬거나, 연설을 준비할 때도 활용할 수 있습니다.', ft:['입력 중 실시간 카운트','단어 수와 문자 수 (공백 포함/미포함)','문장 수와 단락 수','예상 읽기 및 발표 시간','SEO를 위한 키워드 밀도'], hh:'단어 카운터 사용 방법', st:['텍스트 상자에 텍스트를 붙여넣거나 입력하세요','지표가 즉시 계산됩니다','텍스트 하단의 통계를 확인하세요'], lh:'일반적인 단어 수 제한', c1:'문서 유형', c2:'일반적인 범위', rw:[['블로그 게시물','800-2,000 단어'],['학술 논문','3,000-8,000 단어'],['소설','80,000-100,000 단어'],['트윗','280자까지']], fq:[['단어는 어떻게 카운트됩니까?','단어는 공백이나 줄 바꿈으로 구분된 비공백 문자의 연속으로 정의됩니다.'],['문자 수에 공백이 포함됩니까?','공백 포함과 공백 제외 두 가지 지표 모두 표시합니다.'],['읽기 시간은 어떻게 계산됩니까?','성인의 평균 읽기 속도 200-250 단어/분을 기준으로 계산합니다.']] }
};
for(const[l,t] of Object.entries(wcLangs)){const h=mkWC(t);if(fix(wc,l,h)){n++;console.log('WC '+l+' -> '+h.length);}}
// Also extend hi and es which are just under MIN
['hi','es'].forEach(l=>{const e=(wc[l]&&wc[l].contentHtml)||'';if(e.length>0&&e.length<MIN){wc[l].contentHtml=e+'<section class="space-y-4"><p class="text-slate-600 dark:text-slate-400">'+( l==='hi'?'Hamaara shabda sankhyak aapko vastavik samay mein aapke lekhan ki sahayata karta hai. Sahi shabdon ki sankhya aur sahee praaroop aapki SEO ranking mein sahayata kar sakta hai.':'Nuestro contador de palabras le ayuda en tiempo real. El recuento correcto y el formato adecuado pueden mejorar su clasificacion SEO y la legibilidad del contenido.' )+'</p></section>';n++;console.log('WC '+l+' extended to '+wc[l].contentHtml.length);}});
wr('word-counter',wc);

// ===== TOOL PAGES =====
const toolDefs = {
  'image-compressor': {
    fr:{h1:"Compresseur d'images en ligne gratuit",d:"Compressez vos images JPEG, PNG et WebP en ligne sans perte de qualite visible. Notre outil gratuit optimise vos images pour le web sans necessite d'installation.",hh:'Comment utiliser',s:["Telechargez votre image (JPEG, PNG ou WebP)","Choisissez le niveau de qualite souhaite","Telechargez l'image compressee"],fh:'Fonctionnalites principales',f:["Compression sans perte visible de qualite","JPEG, PNG, WebP pris en charge","Traitement entierement dans le navigateur","Gratuit et sans inscription requise"],q:[["Quels formats sont pris en charge?","JPEG, PNG et WebP."],["La qualite se degrade-t-elle?","Nous utilisons des algorithmes intelligents pour une perte minimale de qualite."],["Les images sont-elles stockees sur un serveur?","Non, tout le traitement se fait dans votre navigateur."],["Quelle est la taille maximale?","La plupart des navigateurs prennent en charge jusqu'a 100 Mo."]]},
    de:{h1:"Kostenloser Online-Bildkompressor",d:"Komprimieren Sie Ihre JPEG-, PNG- und WebP-Bilder online ohne sichtbaren Qualitatsverlust. Kein Download, keine Registrierung erforderlich.",hh:'Verwendung',s:['Laden Sie Ihr Bild hoch (JPEG, PNG oder WebP)','Wahlen Sie die gewunschte Qualitatsstufe','Laden Sie das komprimierte Bild herunter'],fh:'Hauptfunktionen',f:['Komprimierung ohne sichtbaren Qualitatsverlust','JPEG, PNG, WebP unterstutzt','Verarbeitung vollstandig im Browser','Kostenlos und ohne Anmeldung'],q:[['Welche Formate werden unterstutzt?','JPEG, PNG und WebP.'],['Verliert das Bild an Qualitat?','Wir verwenden intelligente Algorithmen fur minimalen Verlust.'],['Werden Bilder auf einem Server gespeichert?','Nein, alles wird in Ihrem Browser verarbeitet.'],['Was ist die maximale Dateigrosse?','Die meisten Browser unterstutzen bis zu 100 MB.']]},
    pt:{h1:"Compressor de Imagem Online Gratuito",d:"Comprima suas imagens JPEG, PNG e WebP online sem perda visivel de qualidade. Sem download, sem cadastro necessario.",hh:'Como usar',s:['Envie sua imagem (JPEG, PNG ou WebP)','Escolha o nivel de qualidade desejado','Baixe a imagem comprimida'],fh:'Principais recursos',f:['Compressao sem perda visivel de qualidade','JPEG, PNG, WebP suportados','Processamento totalmente no navegador','Gratuito e sem cadastro'],q:[['Quais formatos sao suportados?','JPEG, PNG e WebP.'],['A qualidade piora?','Usamos algoritmos inteligentes para perda minima.'],['As imagens sao armazenadas em servidor?','Nao, tudo e processado no seu navegador.'],['Qual e o tamanho maximo?','A maioria dos navegadores suporta ate 100 MB.']]},
    it:{h1:"Compressore di Immagini Online Gratuito",d:"Comprimi le tue immagini JPEG, PNG e WebP online senza perdita visibile di qualita. Nessun download, nessuna registrazione richiesta.",hh:'Come usare',s:["Carica la tua immagine (JPEG, PNG o WebP)","Scegli il livello di qualita desiderato","Scarica l'immagine compressa"],fh:'Funzionalita principali',f:["Compressione senza perdita visibile di qualita","JPEG, PNG, WebP supportati","Elaborazione completamente nel browser","Gratuito e senza registrazione"],q:[["Quali formati sono supportati?","JPEG, PNG e WebP."],["La qualita peggiora?","Usiamo algoritmi intelligenti per una perdita minima."],["Le immagini vengono memorizzate su un server?","No, tutto viene elaborato nel tuo browser."],["Qual e la dimensione massima?","La maggior parte dei browser supporta fino a 100 MB."]]},
    ja:{h1:"無料オンライン画像圧縮ツール",d:"JPEG、PNG、WebP画像をオンラインで品質の損失なく圧縮します。ダウンロードや登録は不要です。",hh:'使い方',s:['画像をアップロードする（JPEG、PNG、WebP）','希望の品質レベルを選択する','圧縮された画像をダウンロードする'],fh:'主な機能',f:['目に見える品質損失なしの圧縮','JPEG、PNG、WebPに対応','ブラウザ内で完全に処理','無料・登録不要'],q:[['どのフォーマットがサポートされていますか？','JPEG、PNG、WebPです。'],['品質は劣化しますか？','最小限の損失のためのスマートアルゴリズムを使用します。'],['画像はサーバーに保存されますか？','いいえ、すべてブラウザで処理されます。'],['最大ファイルサイズは？','ほとんどのブラウザは100MBまでサポートします。']]},
    ko:{h1:"무료 온라인 이미지 압축기",d:"JPEG, PNG, WebP 이미지를 온라인에서 눈에 띄는 품질 손실 없이 압축합니다. 다운로드나 등록이 필요 없습니다.",hh:'사용 방법',s:['이미지를 업로드하세요 (JPEG, PNG, WebP)','원하는 품질 수준을 선택하세요','압축된 이미지를 다운로드하세요'],fh:'주요 기능',f:['눈에 띄는 품질 손실 없는 압축','JPEG, PNG, WebP 지원','브라우저 내에서 완전히 처리','무료 및 등록 불필요'],q:[['어떤 형식이 지원됩니까?','JPEG, PNG, WebP입니다.'],['품질이 저하됩니까?','최소한의 손실을 위한 스마트 알고리즘을 사용합니다.'],['이미지가 서버에 저장됩니까?','아니요, 모두 브라우저에서 처리됩니다.'],['최대 파일 크기는?','대부분의 브라우저는 100MB까지 지원합니다.']]}
  },
  'jpg-to-png': {
    hi:{h1:'JPG se PNG Converter Online',d:'Apni JPEG files ko muft mein PNG format mein badlen. PNG transparency aur lossless compression ka samarthan karta hai jo graphs, logos aur transparent images ke liye ideal hai.',hh:'Kaise Upyog Karein',s:['Apni JPG/JPEG image upload karein','Rupaantaran browser mein svachaalit roop se hoga','PNG file download karein'],fh:'Mukhya Visheshataen',f:['Browser mein poora prasansakaran','Koi installation ya signup ki jarurat nahin','Muft aur asimit upyog','Uchch gunvatta lossless rupaantaran'],q:[['JPG se PNG kyun convert karein?','PNG transparent background aur lossless quality ka samarthan karta hai, logos aur web graphics ke liye aadarsh.'],['Kya gunvatta khoti hai?','Nahin, PNG ek lossless format hai isliye koi gunvatta hani nahin hoti.'],['Kitni badi files convert ho sakti hain?','Browser memory par nirbhar karta hai, samanyatah bade files ke liye.'],['Kya files server par upload hoti hain?','Nahin, sabhi prasansakaran aapke browser mein hota hai.']]},
    es:{h1:'Convertidor JPG a PNG Online',d:'Convierte tus archivos JPEG a PNG de forma gratuita. PNG admite transparencia y compresion sin perdida, ideal para graficos, logos e imagenes con fondo transparente.',hh:'Como usar',s:['Suba su imagen JPG/JPEG','La conversion ocurre automaticamente en el navegador','Descargue el archivo PNG'],fh:'Caracteristicas principales',f:['Procesamiento completo en el navegador','Sin instalacion ni registro','Gratuito e ilimitado','Conversion de alta calidad sin perdida'],q:[['Por que convertir JPG a PNG?','PNG admite fondos transparentes y calidad sin perdida, ideal para logos y graficos web.'],['Se pierde calidad?','No, PNG es un formato sin perdida por lo que no hay degradacion de calidad.'],['Que tamano de archivos se pueden convertir?','Depende de la memoria del navegador, generalmente archivos grandes.'],['Los archivos se suben al servidor?','No, todo el procesamiento ocurre en su navegador.']]},
    fr:{h1:'Convertisseur JPG en PNG en ligne',d:"Convertissez vos fichiers JPEG en PNG gratuitement. PNG prend en charge la transparence et la compression sans perte, ideal pour les graphiques, logos et images a fond transparent.",hh:'Comment utiliser',s:["Telechargez votre image JPG/JPEG","La conversion s'effectue automatiquement dans le navigateur","Telechargez le fichier PNG"],fh:'Fonctionnalites principales',f:["Traitement complet dans le navigateur","Aucune installation ni inscription","Gratuit et illimite","Conversion sans perte de haute qualite"],q:[["Pourquoi convertir JPG en PNG?","PNG prend en charge les arriere-plans transparents et la qualite sans perte, ideal pour les logos et graphiques web."],["Y a-t-il une perte de qualite?","Non, PNG est un format sans perte donc il n'y a pas de degradation de qualite."],["Quelle taille de fichiers peut etre convertie?","Cela depend de la memoire du navigateur."],["Les fichiers sont-ils telecharges sur le serveur?","Non, tout le traitement se passe dans votre navigateur."]]},
    de:{h1:'JPG zu PNG Konverter Online',d:'Konvertieren Sie Ihre JPEG-Dateien kostenlos in PNG. PNG unterstutzt Transparenz und verlustfreie Komprimierung, ideal fur Grafiken, Logos und Bilder mit transparentem Hintergrund.',hh:'Verwendung',s:['Laden Sie Ihr JPG/JPEG-Bild hoch','Die Konvertierung erfolgt automatisch im Browser','Laden Sie die PNG-Datei herunter'],fh:'Hauptfunktionen',f:['Vollstandige Verarbeitung im Browser','Keine Installation oder Anmeldung','Kostenlos und unbegrenzt','Verlustfreie Hochqualitatskonvertierung'],q:[['Warum JPG in PNG konvertieren?','PNG unterstutzt transparente Hintergrunde und verlustfreie Qualitat, ideal fur Logos und Web-Grafiken.'],['Geht Qualitat verloren?','Nein, PNG ist ein verlustfreies Format, daher gibt es keine Qualitatsverschlechterung.'],['Welche Dateigrosse kann konvertiert werden?','Hangt vom Browser-Speicher ab.'],['Werden Dateien auf den Server hochgeladen?','Nein, die gesamte Verarbeitung findet in Ihrem Browser statt.']]},
    pt:{h1:'Conversor JPG para PNG Online',d:'Converta seus arquivos JPEG para PNG gratuitamente. PNG suporta transparencia e compressao sem perdas, ideal para graficos, logos e imagens com fundo transparente.',hh:'Como usar',s:['Envie sua imagem JPG/JPEG','A conversao ocorre automaticamente no navegador','Baixe o arquivo PNG'],fh:'Principais recursos',f:['Processamento completo no navegador','Sem instalacao ou cadastro','Gratuito e ilimitado','Conversao de alta qualidade sem perdas'],q:[['Por que converter JPG para PNG?','PNG suporta fundos transparentes e qualidade sem perdas, ideal para logos e graficos web.'],['Ha perda de qualidade?','Nao, PNG e um formato sem perdas, portanto nao ha degradacao de qualidade.'],['Qual tamanho de arquivo pode ser convertido?','Depende da memoria do navegador.'],['Os arquivos sao enviados ao servidor?','Nao, todo o processamento ocorre no seu navegador.']]},
    it:{h1:'Convertitore JPG in PNG Online',d:"Converti i tuoi file JPEG in PNG gratuitamente. PNG supporta la trasparenza e la compressione senza perdita, ideale per grafici, loghi e immagini con sfondo trasparente.",hh:'Come usare',s:['Carica la tua immagine JPG/JPEG','La conversione avviene automaticamente nel browser','Scarica il file PNG'],fh:'Funzionalita principali',f:['Elaborazione completa nel browser','Nessuna installazione o registrazione','Gratuito e illimitato','Conversione di alta qualita senza perdita'],q:[["Perche convertire JPG in PNG?","PNG supporta sfondi trasparenti e qualita senza perdita, ideale per loghi e grafica web."],["C'e perdita di qualita?","No, PNG e un formato senza perdita quindi non c'e degradazione della qualita."],["Che dimensione di file puo essere convertita?","Dipende dalla memoria del browser."],["I file vengono caricati sul server?","No, tutta l'elaborazione avviene nel tuo browser."]]},
    ja:{h1:'JPGからPNG変換ツール（オンライン無料）',d:'JPEGファイルを無料でPNGに変換します。PNGは透過性とロスレス圧縮をサポートし、グラフィックス、ロゴ、透明背景の画像に最適です。',hh:'使い方',s:['JPG/JPEG画像をアップロードする','変換がブラウザで自動的に行われる','PNGファイルをダウンロードする'],fh:'主な機能',f:['ブラウザ内で完全に処理','インストールやサインアップ不要','無料・無制限','ロスレス高品質変換'],q:[['なぜJPGをPNGに変換するのですか？','PNGは透明な背景とロスレス品質をサポートし、ロゴやWebグラフィックスに最適です。'],['品質は失われますか？','いいえ、PNGはロスレスフォーマットなので品質劣化はありません。'],['どのくらいのファイルサイズを変換できますか？','ブラウザのメモリに依存します。'],['ファイルはサーバーにアップロードされますか？','いいえ、すべての処理はブラウザ内で行われます。']]},
    ko:{h1:'JPG에서 PNG 변환기 (온라인 무료)',d:'JPEG 파일을 무료로 PNG로 변환하세요. PNG는 투명성과 무손실 압축을 지원하며 그래픽, 로고, 투명 배경 이미지에 이상적입니다.',hh:'사용 방법',s:['JPG/JPEG 이미지를 업로드하세요','변환이 브라우저에서 자동으로 이루어집니다','PNG 파일을 다운로드하세요'],fh:'주요 기능',f:['브라우저 내에서 완전히 처리','설치나 가입 불필요','무료 및 무제한','무손실 고품질 변환'],q:[['JPG를 PNG로 변환하는 이유는?','PNG는 투명한 배경과 무손실 품질을 지원하며 로고 및 웹 그래픽에 이상적입니다.'],['품질이 손실됩니까?','아니요, PNG는 무손실 형식이므로 품질 저하가 없습니다.'],['어떤 파일 크기를 변환할 수 있습니까?','브라우저 메모리에 따라 다릅니다.'],['파일이 서버에 업로드됩니까?','아니요, 모든 처리는 브라우저 내에서 이루어집니다.']]}
  },
  'png-to-jpg': {
    hi:{h1:'PNG se JPG Converter Online',d:'PNG files ko JPG/JPEG format mein muft mein badlen. JPG files aakar mein chhoti hoti hain aur social media, email aur web publishing ke liye aadarshal hain.',hh:'Kaise Upyog Karein',s:['PNG image upload karein','Prishthabhumi rang chunein (transparent kshetron ke liye)','JPG file download karein'],fh:'Mukhya Visheshataen',f:['Transparent kshetron ke liye custom background color','Browser mein poora prasansakaran','Muft aur asimit upyog','Tez rupaantaran'],q:[['PNG ko JPG mein kyun badlen?','JPG files PNG se chhoti hoti hain, social sharing, email aur web use ke liye behatar.'],['Transparency ka kya hota hai?','JPG transparency ka samarthan nahin karta. Transparent kshetr chunin gaye background rang se bhare jaayenge.'],['Kya gunvatta khoti hai?','Thodi ho sakti hai kyunki JPG ek lossy format hai. Aap quality level choose kar sakte hain.'],['Kya files server par upload hoti hain?','Nahin, sabhi prasansakaran aapke browser mein hota hai.']]},
    es:{h1:'Convertidor PNG a JPG Online',d:'Convierte archivos PNG a formato JPG/JPEG gratuitamente. Los archivos JPG son mas pequenos y perfectos para redes sociales, correo electronico y publicacion web.',hh:'Como usar',s:['Suba su imagen PNG','Elija el color de fondo (para areas transparentes)','Descargue el archivo JPG'],fh:'Caracteristicas principales',f:['Color de fondo personalizable para transparencias','Procesamiento completo en el navegador','Gratuito e ilimitado','Conversion rapida'],q:[['Por que convertir PNG a JPG?','Los archivos JPG son mas pequenos, perfectos para redes sociales, correo electronico y uso web.'],['Que pasa con la transparencia?','JPG no admite transparencia. Las areas transparentes se rellenaran con el color de fondo elegido.'],['Hay perdida de calidad?','Algo, ya que JPG es un formato con perdida. Puede elegir el nivel de calidad.'],['Los archivos se suben al servidor?','No, todo el procesamiento ocurre en su navegador.']]},
    fr:{h1:'Convertisseur PNG en JPG en ligne',d:"Convertissez des fichiers PNG au format JPG/JPEG gratuitement. Les fichiers JPG sont plus petits et parfaits pour les reseaux sociaux, les e-mails et la publication web.",hh:'Comment utiliser',s:["Telechargez votre image PNG","Choisissez la couleur de fond (pour les zones transparentes)","Telechargez le fichier JPG"],fh:'Fonctionnalites principales',f:["Couleur de fond personnalisable pour les transparences","Traitement complet dans le navigateur","Gratuit et illimite","Conversion rapide"],q:[["Pourquoi convertir PNG en JPG?","Les fichiers JPG sont plus petits, parfaits pour les reseaux sociaux, les e-mails et l'utilisation web."],["Qu'arrive-t-il a la transparence?","JPG ne prend pas en charge la transparence. Les zones transparentes seront remplies avec la couleur de fond choisie."],["Y a-t-il une perte de qualite?","Un peu, car JPG est un format avec perte. Vous pouvez choisir le niveau de qualite."],["Les fichiers sont-ils telecharges sur le serveur?","Non, tout le traitement se passe dans votre navigateur."]]},
    de:{h1:'PNG zu JPG Konverter Online',d:'Konvertieren Sie PNG-Dateien kostenlos in JPG/JPEG-Format. JPG-Dateien sind kleiner und perfekt fur soziale Medien, E-Mails und Webpublishing.',hh:'Verwendung',s:['Laden Sie Ihr PNG-Bild hoch','Wahlen Sie Hintergrundfarbe (fur transparente Bereiche)','Laden Sie die JPG-Datei herunter'],fh:'Hauptfunktionen',f:['Anpassbare Hintergrundfarbe fur Transparenzen','Vollstandige Verarbeitung im Browser','Kostenlos und unbegrenzt','Schnelle Konvertierung'],q:[['Warum PNG in JPG konvertieren?','JPG-Dateien sind kleiner, perfekt fur soziale Medien, E-Mails und Web-Nutzung.'],['Was passiert mit Transparenz?','JPG unterstutzt keine Transparenz. Transparente Bereiche werden mit der gewahlten Hintergrundfarbe gefullt.'],['Gibt es Qualitatsverlust?','Etwas, da JPG ein verlustbehaftetes Format ist. Sie konnen das Qualitatsniveau wahlen.'],['Werden Dateien auf den Server hochgeladen?','Nein, die gesamte Verarbeitung findet in Ihrem Browser statt.']]},
    pt:{h1:'Conversor PNG para JPG Online',d:'Converta arquivos PNG para o formato JPG/JPEG gratuitamente. Arquivos JPG sao menores e perfeitos para redes sociais, e-mail e publicacao na web.',hh:'Como usar',s:['Envie sua imagem PNG','Escolha a cor de fundo (para areas transparentes)','Baixe o arquivo JPG'],fh:'Principais recursos',f:['Cor de fundo personalizavel para transparencias','Processamento completo no navegador','Gratuito e ilimitado','Conversao rapida'],q:[['Por que converter PNG para JPG?','Arquivos JPG sao menores, perfeitos para redes sociais, e-mail e uso na web.'],['O que acontece com a transparencia?','JPG nao suporta transparencia. As areas transparentes serao preenchidas com a cor de fundo escolhida.'],['Ha perda de qualidade?','Um pouco, pois JPG e um formato com perda. Voce pode escolher o nivel de qualidade.'],['Os arquivos sao enviados ao servidor?','Nao, todo o processamento ocorre no seu navegador.']]},
    it:{h1:'Convertitore PNG in JPG Online',d:"Converti file PNG nel formato JPG/JPEG gratuitamente. I file JPG sono piu piccoli e perfetti per i social media, le email e la pubblicazione web.",hh:'Come usare',s:["Carica la tua immagine PNG","Scegli il colore di sfondo (per le aree trasparenti)","Scarica il file JPG"],fh:'Funzionalita principali',f:["Colore di sfondo personalizzabile per le trasparenze","Elaborazione completa nel browser","Gratuito e illimitato","Conversione rapida"],q:[["Perche convertire PNG in JPG?","I file JPG sono piu piccoli, perfetti per i social media, le email e l'uso web."],["Cosa succede alla trasparenza?","JPG non supporta la trasparenza. Le aree trasparenti verranno riempite con il colore di sfondo scelto."],["C'e perdita di qualita?","Un po', poiche JPG e un formato con perdita. Puoi scegliere il livello di qualita."],["I file vengono caricati sul server?","No, tutta l'elaborazione avviene nel tuo browser."]]},
    ja:{h1:'PNGからJPG変換ツール（オンライン無料）',d:'PNGファイルを無料でJPG/JPEG形式に変換します。JPGファイルはサイズが小さく、ソーシャルメディア、メール、Web公開に最適です。',hh:'使い方',s:['PNG画像をアップロードする','背景色を選択する（透明部分用）','JPGファイルをダウンロードする'],fh:'主な機能',f:['透明部分用のカスタム背景色','ブラウザ内で完全に処理','無料・無制限','高速変換'],q:[['なぜPNGをJPGに変換するのですか？','JPGファイルはサイズが小さく、ソーシャルメディア、メール、Web使用に最適です。'],['透明性はどうなりますか？','JPGは透過をサポートしません。透明部分は選択した背景色で塗りつぶされます。'],['品質は失われますか？','わずかに、JPGはロッシーフォーマットです。品質レベルを選択できます。'],['ファイルはサーバーにアップロードされますか？','いいえ、すべての処理はブラウザ内で行われます。']]},
    ko:{h1:'PNG에서 JPG 변환기 (온라인 무료)',d:'PNG 파일을 무료로 JPG/JPEG 형식으로 변환하세요. JPG 파일은 더 작으며 소셜 미디어, 이메일, 웹 게시에 이상적입니다.',hh:'사용 방법',s:['PNG 이미지를 업로드하세요','배경 색상을 선택하세요 (투명 영역용)','JPG 파일을 다운로드하세요'],fh:'주요 기능',f:['투명 영역을 위한 사용자 정의 배경 색상','브라우저 내에서 완전히 처리','무료 및 무제한','빠른 변환'],q:[['PNG를 JPG로 변환하는 이유는?','JPG 파일은 더 작고 소셜 미디어, 이메일, 웹 사용에 이상적입니다.'],['투명성은 어떻게 됩니까?','JPG는 투명성을 지원하지 않습니다. 투명 영역은 선택한 배경 색상으로 채워집니다.'],['품질이 손실됩니까?','약간, JPG는 손실 형식입니다. 품질 수준을 선택할 수 있습니다.'],['파일이 서버에 업로드됩니까?','아니요, 모든 처리는 브라우저 내에서 이루어집니다.']]}
  },
  'json-formatter': {
    hi:{h1:'JSON Formatter Online - JSON ko Format aur Beautify Karein',d:'JSON ko online format karein, satpapit karein aur sundar banaen. Minified JSON ko structured, padhne yogya format mein badlen. Debugging aur development ke liye aadarsh.',hh:'Kaise Upyog Karein',s:['JSON paste karein ya type karein','Format ya Beautify button dabaaen','Formatted JSON copy karein ya download karein'],fh:'Mukhya Visheshataen',f:['Real-time JSON beautification','Vaakyansh truti pahachaan aur highlighting','JSON minification','JSON satpapit karan','Syntax highlighting'],q:[['JSON formatter ka upyog kyun karein?','Minified JSON ek single line mein hota hai jo padhna mushkil hai. Formatter ise readable hierarchy mein convert karta hai.'],['Kya mera JSON surakshit hai?','Haan, sabhi prasansakaran aapke browser mein hota hai. Koi data server par nahin bheja jata.'],['JSON kya hai?','JavaScript Object Notation ek halka data-interchange format hai jo padh aur likha ja sakta hai.'],['Mein JSON ko minify kaise karun?','Formatter mein Minify option ka upyog karein jo format JSON ko ek compact single-line string mein convert karta hai.']]},
    es:{h1:'Formateador JSON Online - Formatee y Embellezca JSON',d:'Formatee, valide y embellezca JSON en linea. Convierta JSON minificado en un formato legible y estructurado. Ideal para depuracion y desarrollo.',hh:'Como usar',s:['Pegue o escriba su JSON','Pulse el boton Formatear o Embellecer','Copie o descargue el JSON formateado'],fh:'Caracteristicas principales',f:['Embellecimiento JSON en tiempo real','Deteccion y resaltado de errores de sintaxis','Minificacion JSON','Validacion JSON','Resaltado de sintaxis'],q:[['Por que usar un formateador JSON?','El JSON minificado esta en una sola linea, dificil de leer. El formateador lo convierte en una jerarquia legible.'],['Mi JSON es seguro?','Si, todo el procesamiento ocurre en su navegador. No se envian datos al servidor.'],['Que es JSON?','JavaScript Object Notation es un formato ligero de intercambio de datos que los humanos pueden leer y escribir.'],['Como minifico JSON?','Use la opcion Minify en el formateador que convierte JSON formateado en una cadena compacta de una sola linea.']]},
    fr:{h1:'Formateur JSON en Ligne - Formatez et Embellissez JSON',d:"Formatez, validez et embellissez JSON en ligne. Convertissez JSON minifie en un format lisible et structure. Ideal pour le debogage et le developpement.",hh:'Comment utiliser',s:["Collez ou tapez votre JSON","Cliquez sur le bouton Formater ou Embellir","Copiez ou telechargez le JSON formate"],fh:'Fonctionnalites principales',f:["Embellissement JSON en temps reel","Detection et mise en evidence des erreurs de syntaxe","Minification JSON","Validation JSON","Coloration syntaxique"],q:[["Pourquoi utiliser un formateur JSON?","Le JSON minifie est sur une seule ligne, difficile a lire. Le formateur le convertit en une hierarchie lisible."],["Mon JSON est-il securise?","Oui, tout le traitement se passe dans votre navigateur. Aucune donnee n'est envoyee au serveur."],["Qu'est-ce que JSON?","JavaScript Object Notation est un format d'echange de donnees leger que les humains peuvent lire et ecrire."],["Comment minifier JSON?","Utilisez l'option Minify dans le formateur qui convertit le JSON formate en une chaine compacte."]]},
    de:{h1:'Online JSON Formatter - JSON Formatieren und Verschonern',d:'Formatieren, validieren und verschonern Sie JSON online. Konvertieren Sie minimierten JSON in ein lesbares, strukturiertes Format. Ideal zum Debuggen und Entwickeln.',hh:'Verwendung',s:['Fugen Sie Ihren JSON ein oder tippen Sie ihn ein','Klicken Sie auf Formatieren oder Verschonern','Kopieren oder herunterladen Sie den formatierten JSON'],fh:'Hauptfunktionen',f:['Echtzeit-JSON-Verschonerung','Syntaxfehlererkennung und -hervorhebung','JSON-Minifizierung','JSON-Validierung','Syntaxhervorhebung'],q:[['Warum einen JSON-Formatter verwenden?','Minifizierter JSON ist in einer einzigen Zeile, schwer lesbar. Der Formatter konvertiert ihn in eine lesbare Hierarchie.'],['Ist mein JSON sicher?','Ja, die gesamte Verarbeitung findet in Ihrem Browser statt. Keine Daten werden an den Server gesendet.'],['Was ist JSON?','JavaScript Object Notation ist ein leichtes Datenaustauschformat, das Menschen lesen und schreiben konnen.'],['Wie minifiziere ich JSON?','Verwenden Sie die Minify-Option im Formatter, die formatierten JSON in eine kompakte Zeichenkette konvertiert.']]},
    pt:{h1:'Formatador JSON Online - Formate e Embeleze JSON',d:'Formate, valide e embeleze JSON online. Converta JSON minificado em um formato legivel e estruturado. Ideal para depuracao e desenvolvimento.',hh:'Como usar',s:['Cole ou digite seu JSON','Clique no botao Formatar ou Embelezar','Copie ou baixe o JSON formatado'],fh:'Principais recursos',f:['Embelezamento JSON em tempo real','Deteccao e destaque de erros de sintaxe','Minificacao JSON','Validacao JSON','Destaque de sintaxe'],q:[['Por que usar um formatador JSON?','JSON minificado esta em uma unica linha, dificil de ler. O formatador o converte em uma hierarquia legivel.'],['Meu JSON e seguro?','Sim, todo o processamento ocorre no seu navegador. Nenhum dado e enviado ao servidor.'],['O que e JSON?','JavaScript Object Notation e um formato leve de troca de dados que humanos podem ler e escrever.'],['Como minifico JSON?','Use a opcao Minify no formatador que converte JSON formatado em uma string compacta.']]},
    it:{h1:'Formattatore JSON Online - Formatta e Abbellisci JSON',d:"Formatta, valida e abbellisci JSON online. Converti JSON minificato in un formato leggibile e strutturato. Ideale per il debugging e lo sviluppo.",hh:'Come usare',s:["Incolla o digita il tuo JSON","Clicca sul pulsante Formatta o Abbellisci","Copia o scarica il JSON formattato"],fh:'Funzionalita principali',f:["Abbellimento JSON in tempo reale","Rilevamento ed evidenziazione degli errori di sintassi","Minificazione JSON","Validazione JSON","Evidenziazione della sintassi"],q:[["Perche usare un formattatore JSON?","Il JSON minificato e su una singola riga, difficile da leggere. Il formattatore lo converte in una gerarchia leggibile."],["Il mio JSON e sicuro?","Si, tutta l'elaborazione avviene nel tuo browser. Nessun dato viene inviato al server."],["Cos'e JSON?","JavaScript Object Notation e un formato leggero per lo scambio di dati che gli esseri umani possono leggere e scrivere."],["Come minifico JSON?","Usa l'opzione Minify nel formattatore che converte il JSON formattato in una stringa compatta."]]},
    ja:{h1:'オンラインJSONフォーマッター - JSONのフォーマットと美化',d:'JSONをオンラインでフォーマット、検証、美化します。圧縮されたJSONを読みやすく構造化された形式に変換します。デバッグと開発に最適。',hh:'使い方',s:['JSONを貼り付けるか入力する','フォーマットまたは美化ボタンをクリックする','フォーマットされたJSONをコピーまたはダウンロードする'],fh:'主な機能',f:['リアルタイムJSON美化','構文エラーの検出とハイライト','JSON圧縮','JSON検証','構文ハイライト'],q:[['JSONフォーマッターを使用する理由は？','圧縮されたJSONは1行で読みにくいです。フォーマッターは読みやすい階層に変換します。'],['JSONは安全ですか？','はい、すべての処理はブラウザ内で行われます。サーバーにデータは送られません。'],['JSONとは何ですか？','JavaScript Object Notationは人間が読み書きできる軽量なデータ交換フォーマットです。'],['JSONを圧縮するには？','フォーマッターのMinifyオプションを使用して、フォーマットされたJSONをコンパクトな文字列に変換します。']]},
    ko:{h1:'온라인 JSON 포맷터 - JSON 형식 지정 및 미화',d:'JSON을 온라인으로 형식 지정, 검증 및 미화합니다. 압축된 JSON을 읽기 쉽고 구조화된 형식으로 변환합니다. 디버깅과 개발에 이상적.',hh:'사용 방법',s:['JSON을 붙여넣거나 입력하세요','형식 지정 또는 미화 버튼을 클릭하세요','형식이 지정된 JSON을 복사하거나 다운로드하세요'],fh:'주요 기능',f:['실시간 JSON 미화','구문 오류 감지 및 강조','JSON 압축','JSON 유효성 검사','구문 강조'],q:[['JSON 포맷터를 사용하는 이유는?','압축된 JSON은 한 줄로 읽기 어렵습니다. 포맷터는 읽기 쉬운 계층 구조로 변환합니다.'],['JSON이 안전합니까?','네, 모든 처리는 브라우저 내에서 이루어집니다. 서버에 데이터가 전송되지 않습니다.'],['JSON이란 무엇입니까?','JavaScript Object Notation은 인간이 읽고 쓸 수 있는 경량 데이터 교환 형식입니다.'],['JSON을 압축하려면?','포맷터의 Minify 옵션을 사용하여 형식이 지정된 JSON을 압축된 문자열로 변환합니다.']]}
  },
  'json-validator': {
    hi:{h1:'JSON Validator Online - JSON Satpapit Karein',d:'JSON ko online satpapit karein aur vaakyansh trutiyan khojen. Sunishchit karein ki aapka JSON RFC 8259 manak ke anusar hai. Web development aur API testing ke liye aadarsh.',hh:'Kaise Upyog Karein',s:['Apna JSON paste karein ya type karein','Validate button dabaaen','Trutiyan, chetavaniyan aur suggestions dekhen'],fh:'Mukhya Visheshataen',f:['RFC 8259 anupaalan jaanch','Truti sthan highlighting','Real-time satpapit karan','Schema satpapit karan','Vivaran error messages'],q:[['JSON satpapit karan kyun mahatvapoorn hai?','Amanya JSON APIs ko tod sakta hai, applications crash kar sakti hain. Satpapit karan samasyaon ko pehle deployment pakadta hai.'],['Sabse saamanya JSON trutiyan kya hain?','Anupasthit ya extra double quotes, trailing commas, ya galat bracket pairing.'],['RFC 8259 kya hai?','RFC 8259 JSON data interchange format ke liye official IETF Internet standard hai.'],['Kya mera data surakshit hai?','Haan, sabhi validation aapke browser mein locally hota hai. Koi data server par nahin bheja jata.']]},
    es:{h1:'Validador JSON Online - Valide su JSON',d:'Valide JSON en linea y encuentre errores de sintaxis. Asegurese de que su JSON cumple con el estandar RFC 8259. Ideal para desarrollo web y pruebas de API.',hh:'Como usar',s:['Pegue o escriba su JSON','Pulse el boton Validar','Vea errores, advertencias y sugerencias'],fh:'Caracteristicas principales',f:['Verificacion de cumplimiento RFC 8259','Resaltado de ubicacion de errores','Validacion en tiempo real','Validacion de esquema','Mensajes de error detallados'],q:[['Por que es importante la validacion JSON?','JSON invalido puede romper APIs, hacer que las aplicaciones fallen. La validacion detecta problemas antes del despliegue.'],['Cuales son los errores JSON mas comunes?','Comillas dobles faltantes o extra, comas finales o emparejamiento incorrecto de corchetes.'],['Que es RFC 8259?','RFC 8259 es el estandar oficial de Internet IETF para el formato de intercambio de datos JSON.'],['Mis datos son seguros?','Si, toda la validacion ocurre localmente en su navegador. No se envian datos al servidor.']]},
    fr:{h1:'Validateur JSON en Ligne - Validez votre JSON',d:"Validez JSON en ligne et trouvez les erreurs de syntaxe. Assurez-vous que votre JSON est conforme a la norme RFC 8259. Ideal pour le developpement web et les tests d'API.",hh:'Comment utiliser',s:["Collez ou tapez votre JSON","Cliquez sur le bouton Valider","Consultez les erreurs, avertissements et suggestions"],fh:'Fonctionnalites principales',f:["Verification de conformite RFC 8259","Mise en evidence des erreurs","Validation en temps reel","Validation de schema","Messages d'erreur detailles"],q:[["Pourquoi la validation JSON est-elle importante?","Un JSON invalide peut casser les API et faire planter les applications. La validation detecte les problemes avant le deploiement."],["Quelles sont les erreurs JSON les plus courantes?","Guillemets doubles manquants ou en trop, virgules finales ou mauvais appariement de crochets."],["Qu'est-ce que RFC 8259?","RFC 8259 est la norme Internet officielle IETF pour le format d'echange de donnees JSON."],["Mes donnees sont-elles securisees?","Oui, toute la validation se passe localement dans votre navigateur. Aucune donnee n'est envoyee au serveur."]]},
    de:{h1:'Online JSON Validator - Validieren Sie Ihren JSON',d:'Validieren Sie JSON online und finden Sie Syntaxfehler. Stellen Sie sicher, dass Ihr JSON dem RFC 8259-Standard entspricht. Ideal fur Webentwicklung und API-Tests.',hh:'Verwendung',s:['Fugen Sie Ihren JSON ein oder tippen Sie ihn ein','Klicken Sie auf Validieren','Sehen Sie Fehler, Warnungen und Vorschlage'],fh:'Hauptfunktionen',f:['RFC 8259-Konformitatsprufung','Fehlerstandort-Hervorhebung','Echtzeit-Validierung','Schema-Validierung','Detaillierte Fehlermeldungen'],q:[['Warum ist JSON-Validierung wichtig?','Ungultiges JSON kann APIs beschadigen und Anwendungen zum Absturz bringen. Validierung erkennt Probleme vor der Bereitstellung.'],['Was sind haufige JSON-Fehler?','Fehlende oder zusatzliche doppelte Anfuhrungszeichen, abschliesende Kommas oder falsche Klammerung.'],['Was ist RFC 8259?','RFC 8259 ist der offizielle IETF-Internetstandard fur das JSON-Datenaustauschformat.'],['Sind meine Daten sicher?','Ja, die gesamte Validierung findet lokal in Ihrem Browser statt. Keine Daten werden an den Server gesendet.']]},
    pt:{h1:'Validador JSON Online - Valide seu JSON',d:'Valide JSON online e encontre erros de sintaxe. Certifique-se de que seu JSON esta em conformidade com o padrao RFC 8259. Ideal para desenvolvimento web e testes de API.',hh:'Como usar',s:['Cole ou digite seu JSON','Clique no botao Validar','Veja erros, avisos e sugestoes'],fh:'Principais recursos',f:['Verificacao de conformidade RFC 8259','Destaque de localizacao de erros','Validacao em tempo real','Validacao de esquema','Mensagens de erro detalhadas'],q:[['Por que a validacao JSON e importante?','JSON invalido pode quebrar APIs e fazer as aplicacoes falharem. A validacao detecta problemas antes da implantacao.'],['Quais sao os erros JSON mais comuns?','Aspas duplas ausentes ou extras, virgulas finais ou emparelhamento incorreto de colchetes.'],['O que e RFC 8259?','RFC 8259 e o padrao oficial IETF da Internet para o formato de troca de dados JSON.'],['Meus dados sao seguros?','Sim, toda a validacao ocorre localmente no seu navegador. Nenhum dado e enviado ao servidor.']]},
    it:{h1:'Validatore JSON Online - Valida il tuo JSON',d:"Valida JSON online e trova errori di sintassi. Assicurati che il tuo JSON sia conforme allo standard RFC 8259. Ideale per lo sviluppo web e i test API.",hh:'Come usare',s:['Incolla o digita il tuo JSON','Clicca sul pulsante Valida','Controlla errori, avvisi e suggerimenti'],fh:'Funzionalita principali',f:['Verifica conformita RFC 8259','Evidenziazione posizione errori','Validazione in tempo reale','Validazione schema','Messaggi di errore dettagliati'],q:[["Perche la validazione JSON e importante?","JSON non valido puo rompere le API e far fallire le applicazioni. La validazione rileva i problemi prima del deployment."],["Quali sono gli errori JSON piu comuni?","Virgolette doppie mancanti o extra, virgole finali o abbinamento errato delle parentesi."],["Cos'e RFC 8259?","RFC 8259 e lo standard Internet ufficiale IETF per il formato di scambio dati JSON."],["I miei dati sono sicuri?","Si, tutta la validazione avviene localmente nel tuo browser. Nessun dato viene inviato al server."]]},
    ja:{h1:'オンラインJSONバリデーター - JSONを検証する',d:'JSONをオンラインで検証し、構文エラーを見つけます。JSONがRFC 8259標準に準拠しているか確認します。Web開発とAPIテストに最適。',hh:'使い方',s:['JSONを貼り付けるか入力する','検証ボタンをクリックする','エラー、警告、提案を確認する'],fh:'主な機能',f:['RFC 8259準拠チェック','エラー位置のハイライト','リアルタイム検証','スキーマ検証','詳細なエラーメッセージ'],q:[['JSON検証が重要な理由は？','無効なJSONはAPIを壊し、アプリケーションをクラッシュさせる可能性があります。検証はデプロイ前に問題を検出します。'],['よくあるJSONエラーは？','二重引用符の欠如や余分、末尾のカンマ、または括弧の誤ったペアリング。'],['RFC 8259とは？','RFC 8259はJSONデータ交換フォーマットの公式IETFインターネット標準です。'],['データは安全ですか？','はい、すべての検証はブラウザ内でローカルに行われます。サーバーにデータは送られません。']]},
    ko:{h1:'온라인 JSON 유효성 검사기 - JSON 검증',d:'JSON을 온라인으로 검증하고 구문 오류를 찾습니다. JSON이 RFC 8259 표준을 준수하는지 확인합니다. 웹 개발 및 API 테스트에 이상적.',hh:'사용 방법',s:['JSON을 붙여넣거나 입력하세요','유효성 검사 버튼을 클릭하세요','오류, 경고 및 제안을 확인하세요'],fh:'주요 기능',f:['RFC 8259 준수 검사','오류 위치 강조','실시간 유효성 검사','스키마 유효성 검사','자세한 오류 메시지'],q:[['JSON 검증이 중요한 이유는?','유효하지 않은 JSON은 API를 손상시키고 애플리케이션을 충돌시킬 수 있습니다. 검증은 배포 전에 문제를 감지합니다.'],['일반적인 JSON 오류는?','누락되거나 추가된 큰따옴표, 후행 쉼표 또는 잘못된 괄호 쌍.'],['RFC 8259란?','RFC 8259는 JSON 데이터 교환 형식의 공식 IETF 인터넷 표준입니다.'],['데이터가 안전합니까?','네, 모든 검증은 브라우저 내에서 로컬로 이루어집니다. 서버에 데이터가 전송되지 않습니다.']]}
  },
  'pdf-merge': {
    hi:{h1:'PDF Merge Online - Multiple PDFs ko Ek File mein Milaen',d:'Browser mein ekadhik PDF dastaavez ko ek file mein milaen. Koi installation nahin, koi server upload nahin. Aapke documents poori tarah surakshit rehte hain.',hh:'Kaise Upyog Karein',s:['PDF files upload karein','Drag-and-drop se kram vyavasthit karein','Merge button dabaaen','Merge ki gayi PDF download karein'],fh:'Mukhya Visheshataen',f:['Browser mein poora prasansakaran','Koi file aakaar seema nahin','Drag-and-drop kram','Mool gunvatta aur formatting banae rakhen'],q:[['Kya files server par upload hoti hain?','Nahin. Sabhi prasansakaran aapke browser mein locally hota hai. Aapki files kabhi bhi upload nahin hoti.'],['Kya gunvatta kam hoti hai?','Nahin. PDF merging mool samagri ki gunvatta ko prabhavit nahin karti.'],['Kitni PDF files ek saath merge ho sakti hain?','Koi seema nahin, lekin bahut badi files browser mein dhimi ho sakti hain.'],['Kya PDF merge karna muft hai?','Haan, poori tarah se muft, koi signup ya subscription ki jarurat nahin.']]},
    es:{h1:'Unir PDF Online - Combine Multiples PDFs en Un Solo Archivo',d:'Combine multiples documentos PDF en un solo archivo directamente en el navegador. Sin instalacion, sin subida al servidor. Sus documentos permanecen completamente privados.',hh:'Como usar',s:['Suba sus archivos PDF','Organice el orden con arrastrar y soltar','Pulse el boton Fusionar','Descargue el PDF fusionado'],fh:'Caracteristicas principales',f:['Procesamiento completo en el navegador','Sin limite de tamano de archivo','Organizacion con arrastrar y soltar','Mantiene la calidad y el formato original'],q:[['Los archivos se suben al servidor?','No. Todo el procesamiento ocurre localmente en su navegador. Sus archivos nunca se suben.'],['Se degrada la calidad?','No. La fusion de PDF no afecta la calidad del contenido original.'],['Cuantos archivos PDF se pueden combinar a la vez?','No hay limite, aunque archivos muy grandes pueden ser mas lentos en el navegador.'],['Es gratuita la fusion de PDF?','Si, completamente gratuita, sin necesidad de registro ni suscripcion.']]},
    fr:{h1:'Fusionner PDF en Ligne - Combinez Plusieurs PDF en Un Seul Fichier',d:"Combinez plusieurs documents PDF en un seul fichier directement dans le navigateur. Aucune installation, aucun telechargement vers le serveur. Vos documents restent entierement prives.",hh:'Comment utiliser',s:["Telechargez vos fichiers PDF","Organisez l'ordre par glisser-deposer","Cliquez sur le bouton Fusionner","Telechargez le PDF fusionne"],fh:'Fonctionnalites principales',f:["Traitement complet dans le navigateur","Pas de limite de taille de fichier","Organisation par glisser-deposer","Conserve la qualite et le formatage d'origine"],q:[["Les fichiers sont-ils telecharges sur le serveur?","Non. Tout le traitement se passe localement dans votre navigateur. Vos fichiers ne sont jamais telecharges."],["La qualite se degrade-t-elle?","Non. La fusion de PDF n'affecte pas la qualite du contenu original."],["Combien de fichiers PDF peut-on combiner a la fois?","Pas de limite, bien que les fichiers tres volumineux puissent etre plus lents dans le navigateur."],["La fusion PDF est-elle gratuite?","Oui, completement gratuite, sans inscription ni abonnement."]]},
    de:{h1:'PDF Online Zusammenfuhren - Mehrere PDFs zu einer Datei Kombinieren',d:'Kombinieren Sie mehrere PDF-Dokumente direkt im Browser zu einer Datei. Keine Installation, kein Server-Upload. Ihre Dokumente bleiben vollstandig privat.',hh:'Verwendung',s:['Laden Sie Ihre PDF-Dateien hoch','Ordnen Sie die Reihenfolge per Drag-and-Drop','Klicken Sie auf Zusammenfuhren','Laden Sie das zusammengefuhrte PDF herunter'],fh:'Hauptfunktionen',f:['Vollstandige Verarbeitung im Browser','Keine Dateigroenbeschrankung','Drag-and-Drop-Organisation','Erhalt die ursprungliche Qualitat und Formatierung'],q:[['Werden Dateien auf den Server hochgeladen?','Nein. Die gesamte Verarbeitung findet lokal in Ihrem Browser statt. Ihre Dateien werden nie hochgeladen.'],['Verliert die Qualitat?','Nein. Das Zusammenfuhren von PDFs beeinflusst die Qualitat des Originalinhalts nicht.'],['Wie viele PDF-Dateien konnen auf einmal kombiniert werden?','Keine Begrenzung, obwohl sehr grose Dateien im Browser langsamer sein konnen.'],['Ist PDF zusammenfuhren kostenlos?','Ja, vollstandig kostenlos, keine Anmeldung oder Abonnement erforderlich.']]},
    pt:{h1:'Unir PDF Online - Combine Varios PDFs em Um Unico Arquivo',d:'Combine varios documentos PDF em um unico arquivo diretamente no navegador. Sem instalacao, sem upload para servidor. Seus documentos permanecem completamente privados.',hh:'Como usar',s:['Envie seus arquivos PDF','Organize a ordem com arrastar e soltar','Clique no botao Mesclar','Baixe o PDF mesclado'],fh:'Principais recursos',f:['Processamento completo no navegador','Sem limite de tamanho de arquivo','Organizacao com arrastar e soltar','Manteve a qualidade e formatacao originais'],q:[['Os arquivos sao enviados ao servidor?','Nao. Todo o processamento ocorre localmente no seu navegador. Seus arquivos nunca sao enviados.'],['A qualidade piora?','Nao. Mesclar PDFs nao afeta a qualidade do conteudo original.'],['Quantos arquivos PDF podem ser combinados de uma vez?','Sem limite, embora arquivos muito grandes possam ser mais lentos no navegador.'],['Mesclar PDF e gratuito?','Sim, completamente gratuito, sem necessidade de cadastro ou assinatura.']]},
    it:{h1:'Unisci PDF Online - Combina Piu PDF in Un Unico File',d:"Combina piu documenti PDF in un unico file direttamente nel browser. Nessuna installazione, nessun caricamento al server. I tuoi documenti rimangono completamente privati.",hh:'Come usare',s:["Carica i tuoi file PDF","Organizza l'ordine con trascina e rilascia","Clicca sul pulsante Unisci","Scarica il PDF unito"],fh:'Funzionalita principali',f:["Elaborazione completa nel browser","Nessun limite di dimensione del file","Organizzazione con trascina e rilascia","Mantiene la qualita e la formattazione originali"],q:[["I file vengono caricati sul server?","No. Tutta l'elaborazione avviene localmente nel tuo browser. I tuoi file non vengono mai caricati."],["La qualita peggiora?","No. L'unione di PDF non influisce sulla qualita del contenuto originale."],["Quanti file PDF si possono combinare alla volta?","Nessun limite, anche se file molto grandi possono essere piu lenti nel browser."],["Unire PDF e gratuito?","Si, completamente gratuito, senza necessita di registrazione o abbonamento."]]},
    ja:{h1:'オンラインPDF結合 - 複数のPDFを一つのファイルに結合',d:'ブラウザで複数のPDF文書を一つのファイルに結合します。インストール不要、サーバーアップロード不要。ドキュメントは完全にプライベートに保たれます。',hh:'使い方',s:['PDFファイルをアップロードする','ドラッグ&ドロップで順序を整理する','結合ボタンをクリックする','結合されたPDFをダウンロードする'],fh:'主な機能',f:['ブラウザ内で完全に処理','ファイルサイズ制限なし','ドラッグ&ドロップによる整理','元の品質とフォーマットを維持'],q:[['ファイルはサーバーにアップロードされますか？','いいえ。すべての処理はブラウザ内でローカルに行われます。ファイルはアップロードされません。'],['品質は低下しますか？','いいえ。PDFを結合しても元のコンテンツの品質に影響しません。'],['一度に何個のPDFファイルを結合できますか？','制限はありません。ただし非常に大きなファイルはブラウザ内で遅くなる場合があります。'],['PDF結合は無料ですか？','はい、完全に無料です。サインアップやサブスクリプション不要。']]},
    ko:{h1:'PDF 온라인으로 합치기 - 여러 PDF를 하나의 파일로 결합',d:'브라우저에서 여러 PDF 문서를 하나의 파일로 결합합니다. 설치 불필요, 서버 업로드 없음. 문서는 완전히 비공개로 유지됩니다.',hh:'사용 방법',s:['PDF 파일을 업로드하세요','드래그 앤 드롭으로 순서를 정리하세요','병합 버튼을 클릭하세요','병합된 PDF를 다운로드하세요'],fh:'주요 기능',f:['브라우저 내에서 완전히 처리','파일 크기 제한 없음','드래그 앤 드롭으로 정리','원본 품질과 형식 유지'],q:[['파일이 서버에 업로드됩니까?','아니요. 모든 처리는 브라우저 내에서 로컬로 이루어집니다. 파일은 업로드되지 않습니다.'],['품질이 저하됩니까?','아니요. PDF 병합은 원본 콘텐츠의 품질에 영향을 미치지 않습니다.'],['한 번에 몇 개의 PDF 파일을 결합할 수 있습니까?','제한 없음, 매우 큰 파일은 브라우저에서 더 느릴 수 있습니다.'],['PDF 병합은 무료입니까?','네, 완전히 무료입니다. 가입이나 구독이 필요 없습니다.']]}
  }
};
for(const[toolPage,localeMap] of Object.entries(toolDefs)){
  const d=rd(toolPage);
  for(const[l,t] of Object.entries(localeMap)){const h=mkTool(t);if(fix(d,l,h)){n++;console.log(toolPage+' ['+l+'] -> '+h.length);}}
  wr(toolPage,d);
}

console.log('\nTOTAL FIXED: '+n);
